#!/usr/bin/env python3
import time
import math

#initiation
listmax = int(input("Up to what number? "))
a = [x for x in range(listmax)]
b = [True for x in range(listmax)]
starttime = time.time()

#main
b[0] = False
b[1] = False
seed = 2
sum = 0
while seed < listmax:
	sum += 1
	for x in a:
		if x % seed == 0:
			b[x] = False
	b[seed] = False
	seed = next((x for x in a if b[x] == True), None)
	if seed == None:
		break

#printing
print(time.time()-starttime)
print(sum)
